//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pflegehaushaltsbuch {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pflegehaushaltsbuch.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cash outflow ähnelt.
        /// </summary>
        public static string BookCategory_Auszahlung {
            get {
                return ResourceManager.GetString("BookCategory_Auszahlung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cash inflow ähnelt.
        /// </summary>
        public static string BookCategory_Einzahlung {
            get {
                return ResourceManager.GetString("BookCategory_Einzahlung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storno ähnelt.
        /// </summary>
        public static string BookCategory_Storno {
            get {
                return ResourceManager.GetString("BookCategory_Storno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous balance ähnelt.
        /// </summary>
        public static string BookingTo_Altbestand {
            get {
                return ResourceManager.GetString("BookingTo_Altbestand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank ähnelt.
        /// </summary>
        public static string BookingTo_Bankbestand {
            get {
                return ResourceManager.GetString("BookingTo_Bankbestand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cash ähnelt.
        /// </summary>
        public static string BookingTo_Barbestand {
            get {
                return ResourceManager.GetString("BookingTo_Barbestand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active ähnelt.
        /// </summary>
        public static string ClientActive_Active {
            get {
                return ResourceManager.GetString("ClientActive_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History ähnelt.
        /// </summary>
        public static string ClientActive_History {
            get {
                return ResourceManager.GetString("ClientActive_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inactive ähnelt.
        /// </summary>
        public static string ClientActive_Inactive {
            get {
                return ResourceManager.GetString("ClientActive_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driday ähnelt.
        /// </summary>
        public static string DayOfWeek_Friday {
            get {
                return ResourceManager.GetString("DayOfWeek_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monday ähnelt.
        /// </summary>
        public static string DayOfWeek_Monay {
            get {
                return ResourceManager.GetString("DayOfWeek_Monay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saturday ähnelt.
        /// </summary>
        public static string DayOfWeek_Saturday {
            get {
                return ResourceManager.GetString("DayOfWeek_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sunday ähnelt.
        /// </summary>
        public static string DayOfWeek_Sunday {
            get {
                return ResourceManager.GetString("DayOfWeek_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thursday ähnelt.
        /// </summary>
        public static string DayOfWeek_Thursday {
            get {
                return ResourceManager.GetString("DayOfWeek_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tuesday ähnelt.
        /// </summary>
        public static string DayOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wednesday ähnelt.
        /// </summary>
        public static string DayOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direct debit ähnelt.
        /// </summary>
        public static string Repayment_Direct_Debit {
            get {
                return ResourceManager.GetString("Repayment_Direct_Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        public static string Repayment_None {
            get {
                return ResourceManager.GetString("Repayment_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payout ähnelt.
        /// </summary>
        public static string Repayment_Payout {
            get {
                return ResourceManager.GetString("Repayment_Payout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferred ähnelt.
        /// </summary>
        public static string Repayment_Transfered {
            get {
                return ResourceManager.GetString("Repayment_Transfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Family ähnelt.
        /// </summary>
        public static string Title_Family {
            get {
                return ResourceManager.GetString("Title_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miss ähnelt.
        /// </summary>
        public static string Title_Miss {
            get {
                return ResourceManager.GetString("Title_Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mr ähnelt.
        /// </summary>
        public static string Title_Mr {
            get {
                return ResourceManager.GetString("Title_Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ms ähnelt.
        /// </summary>
        public static string Title_Ms {
            get {
                return ResourceManager.GetString("Title_Ms", resourceCulture);
            }
        }
    }
}
