//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pflegehaushaltsbuch {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pflegehaushaltsbuch.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: {0}
        ///Copyright: © Michael Richter, 2013–2026
        ///
        ///The Care Household Ledger supports outpatient care providers in clearly managing their operational and financial processes.
        ///
        ///Its features include the management of cash and bank balances, office cash accounts, clients, advisors, and employees. The application also provides centralized document management, cash audits, statistical reports, customizable print templates, as well as data backup and recovery functions.
        ///
        ///Free and Open-Source Software
        ///
        ///T [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string about_license {
            get {
                return ResourceManager.GetString("about_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advisor ähnelt.
        /// </summary>
        public static string advisor {
            get {
                return ResourceManager.GetString("advisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advisor could not be changed or added. ähnelt.
        /// </summary>
        public static string advisor_changed_failed {
            get {
                return ResourceManager.GetString("advisor_changed_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advisor was successfully created or changed. ähnelt.
        /// </summary>
        public static string advisor_created_changed {
            get {
                return ResourceManager.GetString("advisor_created_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the advisor? ähnelt.
        /// </summary>
        public static string advisor_delete {
            get {
                return ResourceManager.GetString("advisor_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advisor could not be deleted. ähnelt.
        /// </summary>
        public static string advisor_delete_failed {
            get {
                return ResourceManager.GetString("advisor_delete_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete advisor ähnelt.
        /// </summary>
        public static string advisor_delete_title {
            get {
                return ResourceManager.GetString("advisor_delete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advisors ähnelt.
        /// </summary>
        public static string advisors_export_filename {
            get {
                return ResourceManager.GetString("advisors_export_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advisors were not added. ähnelt.
        /// </summary>
        public static string advisors_import_failed {
            get {
                return ResourceManager.GetString("advisors_import_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advisors were added. ähnelt.
        /// </summary>
        public static string advisors_imported {
            get {
                return ResourceManager.GetString("advisors_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the advisor name. ähnelt.
        /// </summary>
        public static string advisors_name_missing {
            get {
                return ResourceManager.GetString("advisors_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employee &apos;{0}&apos; cannot be deleted because there is an open loan. ähnelt.
        /// </summary>
        public static string asistants_not_deleteable {
            get {
                return ResourceManager.GetString("asistants_not_deleteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employee was not found. ähnelt.
        /// </summary>
        public static string assistant_not_found {
            get {
                return ResourceManager.GetString("assistant_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employee was successfully changed. ähnelt.
        /// </summary>
        public static string assistants_changed {
            get {
                return ResourceManager.GetString("assistants_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employee could not be changed. ähnelt.
        /// </summary>
        public static string assistants_changed_failed {
            get {
                return ResourceManager.GetString("assistants_changed_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employee was successfully created. ähnelt.
        /// </summary>
        public static string assistants_created {
            get {
                return ResourceManager.GetString("assistants_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employee could not be created. ähnelt.
        /// </summary>
        public static string assistants_created_failed {
            get {
                return ResourceManager.GetString("assistants_created_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete &apos;{0}&apos;? All bookings will be lost. ähnelt.
        /// </summary>
        public static string assistants_delete {
            get {
                return ResourceManager.GetString("assistants_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employees ähnelt.
        /// </summary>
        public static string assistants_export_filename {
            get {
                return ResourceManager.GetString("assistants_export_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employees were not added. ähnelt.
        /// </summary>
        public static string assistants_import_failed {
            get {
                return ResourceManager.GetString("assistants_import_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the employee name. ähnelt.
        /// </summary>
        public static string assistants_name_missing {
            get {
                return ResourceManager.GetString("assistants_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The employee cannot be deleted because at least one booking cannot be assigned exactly. ähnelt.
        /// </summary>
        public static string assistants_not_deleteable_book {
            get {
                return ResourceManager.GetString("assistants_not_deleteable_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank bookings ähnelt.
        /// </summary>
        public static string bank_export_filename {
            get {
                return ResourceManager.GetString("bank_export_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entry was not changed. ähnelt.
        /// </summary>
        public static string book_entry_not_changed {
            get {
                return ResourceManager.GetString("book_entry_not_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Booking has already been canceled. ähnelt.
        /// </summary>
        public static string booking_already_canceled {
            get {
                return ResourceManager.GetString("booking_already_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel booking ähnelt.
        /// </summary>
        public static string booking_cancel {
            get {
                return ResourceManager.GetString("booking_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Booking could not be canceled. ähnelt.
        /// </summary>
        public static string booking_canceled_failed {
            get {
                return ResourceManager.GetString("booking_canceled_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Booking was successfully canceled. ähnelt.
        /// </summary>
        public static string booking_canceled_success {
            get {
                return ResourceManager.GetString("booking_canceled_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to cancel this booking? ähnelt.
        /// </summary>
        public static string booking_canceling {
            get {
                return ResourceManager.GetString("booking_canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Booking failed. ähnelt.
        /// </summary>
        public static string booking_failed {
            get {
                return ResourceManager.GetString("booking_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Booking for {0} failed. ähnelt.
        /// </summary>
        public static string booking_for_client_failed {
            get {
                return ResourceManager.GetString("booking_for_client_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no bookings to cancel. ähnelt.
        /// </summary>
        public static string booking_no_booking_canceled {
            get {
                return ResourceManager.GetString("booking_no_booking_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Booking was successful. ähnelt.
        /// </summary>
        public static string booking_sucess {
            get {
                return ResourceManager.GetString("booking_sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Booking(s) successful. ähnelt.
        /// </summary>
        public static string bookings_success {
            get {
                return ResourceManager.GetString("bookings_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bookings ähnelt.
        /// </summary>
        public static string books_export_filename {
            get {
                return ResourceManager.GetString("books_export_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cash book ähnelt.
        /// </summary>
        public static string cash_export_filename {
            get {
                return ResourceManager.GetString("cash_export_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client was not found. ähnelt.
        /// </summary>
        public static string client_not_found {
            get {
                return ResourceManager.GetString("client_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client was not found: {0} ähnelt.
        /// </summary>
        public static string client_not_found_name {
            get {
                return ResourceManager.GetString("client_not_found_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client was successfully created or changed. ähnelt.
        /// </summary>
        public static string clients_changed {
            get {
                return ResourceManager.GetString("clients_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client could not be created or changed. ähnelt.
        /// </summary>
        public static string clients_changed_failed {
            get {
                return ResourceManager.GetString("clients_changed_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete client &apos;{0}&apos; completely? All bank and cash bookings will also be deleted. ähnelt.
        /// </summary>
        public static string clients_delete {
            get {
                return ResourceManager.GetString("clients_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client deletion is not possible because at least one bank booking cannot be assigned exactly. ähnelt.
        /// </summary>
        public static string clients_delete_bank_not_assignable {
            get {
                return ResourceManager.GetString("clients_delete_bank_not_assignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client deletion is not possible because at least one client booking cannot be assigned exactly. ähnelt.
        /// </summary>
        public static string clients_delete_books_not_assignable {
            get {
                return ResourceManager.GetString("clients_delete_books_not_assignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client deletion is not possible because at least one cash booking cannot be assigned exactly. ähnelt.
        /// </summary>
        public static string clients_delete_cash_not_assignable {
            get {
                return ResourceManager.GetString("clients_delete_cash_not_assignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete account ähnelt.
        /// </summary>
        public static string clients_delete_title {
            get {
                return ResourceManager.GetString("clients_delete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the client name. ähnelt.
        /// </summary>
        public static string clients_enter_name {
            get {
                return ResourceManager.GetString("clients_enter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clients ähnelt.
        /// </summary>
        public static string clients_export_filename {
            get {
                return ResourceManager.GetString("clients_export_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clients were added. ähnelt.
        /// </summary>
        public static string clients_imported {
            get {
                return ResourceManager.GetString("clients_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous balance of client {0}. ähnelt.
        /// </summary>
        public static string clients_previous_amount {
            get {
                return ResourceManager.GetString("clients_previous_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a client first. ähnelt.
        /// </summary>
        public static string clients_select_first {
            get {
                return ResourceManager.GetString("clients_select_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company was saved. ähnelt.
        /// </summary>
        public static string company_saved {
            get {
                return ResourceManager.GetString("company_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please create at least one client first. ähnelt.
        /// </summary>
        public static string create_clients_first {
            get {
                return ResourceManager.GetString("create_clients_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user cannot be created because at least one name is already in use. Check the user name, login name, and email address. ähnelt.
        /// </summary>
        public static string createUserFailed {
            get {
                return ResourceManager.GetString("createUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        public static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database backup has been successfully created. ähnelt.
        /// </summary>
        public static string database_backup {
            get {
                return ResourceManager.GetString("database_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database was changed successfully. ähnelt.
        /// </summary>
        public static string database_changed {
            get {
                return ResourceManager.GetString("database_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not connect to the database. ähnelt.
        /// </summary>
        public static string database_connected_failed {
            get {
                return ResourceManager.GetString("database_connected_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a SQL connection. ähnelt.
        /// </summary>
        public static string database_connection_type_missing {
            get {
                return ResourceManager.GetString("database_connection_type_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database was created. ähnelt.
        /// </summary>
        public static string database_created {
            get {
                return ResourceManager.GetString("database_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This creates a new database. If a database with the same name already exists, it will be completely replaced. ähnelt.
        /// </summary>
        public static string database_creating {
            get {
                return ResourceManager.GetString("database_creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login: Admin
        ///Password: admin ähnelt.
        /// </summary>
        public static string database_default_login {
            get {
                return ResourceManager.GetString("database_default_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQL Login ähnelt.
        /// </summary>
        public static string database_default_login_title {
            get {
                return ResourceManager.GetString("database_default_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a database name. ähnelt.
        /// </summary>
        public static string database_enter_name {
            get {
                return ResourceManager.GetString("database_enter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login failed. ähnelt.
        /// </summary>
        public static string database_login_failed {
            get {
                return ResourceManager.GetString("database_login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database not available ähnelt.
        /// </summary>
        public static string database_not_available {
            get {
                return ResourceManager.GetString("database_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to disconnect the database? ähnelt.
        /// </summary>
        public static string database_reset {
            get {
                return ResourceManager.GetString("database_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The database has been successfully restored. Pflegehaushaltsbuch will now restart. ähnelt.
        /// </summary>
        public static string database_restore {
            get {
                return ResourceManager.GetString("database_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The restored database does not contain a cash balance. ähnelt.
        /// </summary>
        public static string database_restore_missing_hardcash {
            get {
                return ResourceManager.GetString("database_restore_missing_hardcash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The restored database does not contain version information. ähnelt.
        /// </summary>
        public static string database_restore_missing_version {
            get {
                return ResourceManager.GetString("database_restore_missing_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The backup has been restored to a new database. The previous database remains unchanged. ähnelt.
        /// </summary>
        public static string database_restore_staging_success {
            get {
                return ResourceManager.GetString("database_restore_staging_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The version table is missing or cannot be accessed. Please contact support. ähnelt.
        /// </summary>
        public static string database_version_table_missing {
            get {
                return ResourceManager.GetString("database_version_table_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data table could not be changed. ähnelt.
        /// </summary>
        public static string datatable_update_failed {
            get {
                return ResourceManager.GetString("datatable_update_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data table was successfully changed. ähnelt.
        /// </summary>
        public static string datatable_updated {
            get {
                return ResourceManager.GetString("datatable_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your day is already defined in your deadline list. ähnelt.
        /// </summary>
        public static string deadlines_day_exist {
            get {
                return ResourceManager.GetString("deadlines_day_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete deadline ähnelt.
        /// </summary>
        public static string deadlines_delete_title {
            get {
                return ResourceManager.GetString("deadlines_delete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected deadline? ähnelt.
        /// </summary>
        public static string deadlines_deleting {
            get {
                return ResourceManager.GetString("deadlines_deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client {0} deadlines ähnelt.
        /// </summary>
        public static string deadlines_export_filename {
            get {
                return ResourceManager.GetString("deadlines_export_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No deadline is selected for changing. ähnelt.
        /// </summary>
        public static string deadlines_no_selection {
            get {
                return ResourceManager.GetString("deadlines_no_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No deadline is selected for deleting. ähnelt.
        /// </summary>
        public static string deadlines_no_selection_delete {
            get {
                return ResourceManager.GetString("deadlines_no_selection_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete failed. ähnelt.
        /// </summary>
        public static string delete_failed {
            get {
                return ResourceManager.GetString("delete_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The changes require a restart. Please wait. ähnelt.
        /// </summary>
        public static string design_restart_required {
            get {
                return ResourceManager.GetString("design_restart_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a description for the receipt. ähnelt.
        /// </summary>
        public static string document_missing_description {
            get {
                return ResourceManager.GetString("document_missing_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No file name was specified. ähnelt.
        /// </summary>
        public static string document_missing_filename {
            get {
                return ResourceManager.GetString("document_missing_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document saved as... ähnelt.
        /// </summary>
        public static string document_saved {
            get {
                return ResourceManager.GetString("document_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter an email address. ähnelt.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string error_caption {
            get {
                return ResourceManager.GetString("error_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data was successfully exported to {0}. ähnelt.
        /// </summary>
        public static string export_success {
            get {
                return ResourceManager.GetString("export_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cash count was successfully changed. ähnelt.
        /// </summary>
        public static string hardmoney_changed {
            get {
                return ResourceManager.GetString("hardmoney_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cash count could not be changed. ähnelt.
        /// </summary>
        public static string hardmoney_changed_failed {
            get {
                return ResourceManager.GetString("hardmoney_changed_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}...Invalid debtor number. ähnelt.
        /// </summary>
        public static string import_clients_invalid_debtor_no {
            get {
                return ResourceManager.GetString("import_clients_invalid_debtor_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}...Only &apos;Frau&apos; or &apos;Herr&apos; are allowed as title. ähnelt.
        /// </summary>
        public static string import_clients_invalid_title {
            get {
                return ResourceManager.GetString("import_clients_invalid_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter text first. ähnelt.
        /// </summary>
        public static string improved_missing_text {
            get {
                return ResourceManager.GetString("improved_missing_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The old license server has been removed. The feedback function will be rebuilt with the new REST API. ähnelt.
        /// </summary>
        public static string improved_removed_license_server {
            get {
                return ResourceManager.GetString("improved_removed_license_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a city. ähnelt.
        /// </summary>
        public static string invalid_city {
            get {
                return ResourceManager.GetString("invalid_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the company name. ähnelt.
        /// </summary>
        public static string invalid_company {
            get {
                return ResourceManager.GetString("invalid_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set a date in a valid range. ähnelt.
        /// </summary>
        public static string invalid_date {
            get {
                return ResourceManager.GetString("invalid_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid email address. ähnelt.
        /// </summary>
        public static string invalid_email {
            get {
                return ResourceManager.GetString("invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your email address. ähnelt.
        /// </summary>
        public static string invalid_email_enter {
            get {
                return ResourceManager.GetString("invalid_email_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your fax number. ähnelt.
        /// </summary>
        public static string invalid_fax {
            get {
                return ResourceManager.GetString("invalid_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid number. ähnelt.
        /// </summary>
        public static string invalid_no {
            get {
                return ResourceManager.GetString("invalid_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a note. ähnelt.
        /// </summary>
        public static string invalid_note {
            get {
                return ResourceManager.GetString("invalid_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your phone number. ähnelt.
        /// </summary>
        public static string invalid_phone {
            get {
                return ResourceManager.GetString("invalid_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a street. ähnelt.
        /// </summary>
        public static string invalid_street {
            get {
                return ResourceManager.GetString("invalid_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a zip code. ähnelt.
        /// </summary>
        public static string invalid_zip {
            get {
                return ResourceManager.GetString("invalid_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid amount. ähnelt.
        /// </summary>
        public static string ioan_invalid_amount {
            get {
                return ResourceManager.GetString("ioan_invalid_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specify the type of repayment. ähnelt.
        /// </summary>
        public static string ioan_missing_repayment {
            get {
                return ResourceManager.GetString("ioan_missing_repayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loan was successfully repaid. ähnelt.
        /// </summary>
        public static string ioan_repaid {
            get {
                return ResourceManager.GetString("ioan_repaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loan repayment by {0} ähnelt.
        /// </summary>
        public static string ioan_repaid_by {
            get {
                return ResourceManager.GetString("ioan_repaid_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loan could not be repaid. ähnelt.
        /// </summary>
        public static string ioan_repaid_failed {
            get {
                return ResourceManager.GetString("ioan_repaid_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no amount to repay. ähnelt.
        /// </summary>
        public static string ioan_repaid_needless {
            get {
                return ResourceManager.GetString("ioan_repaid_needless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loan payout to {0} ähnelt.
        /// </summary>
        public static string ioan_to {
            get {
                return ResourceManager.GetString("ioan_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwords do not match. ähnelt.
        /// </summary>
        public static string keywords_not_equal {
            get {
                return ResourceManager.GetString("keywords_not_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to connect the elements? ähnelt.
        /// </summary>
        public static string layout_connect_elements {
            get {
                return ResourceManager.GetString("layout_connect_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        public static string layout_connect_title {
            get {
                return ResourceManager.GetString("layout_connect_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully saved to database. ähnelt.
        /// </summary>
        public static string layout_saved {
            get {
                return ResourceManager.GetString("layout_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layouts were exported to {0}. ähnelt.
        /// </summary>
        public static string layouts_exported {
            get {
                return ResourceManager.GetString("layouts_exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The license will be checked now.
        ///Please wait. ähnelt.
        /// </summary>
        public static string license_check {
            get {
                return ResourceManager.GetString("license_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your license is valid until {0}.
        ///You still have {1} day(s) remaining. ähnelt.
        /// </summary>
        public static string license_valid_until {
            get {
                return ResourceManager.GetString("license_valid_until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a password in both fields. ähnelt.
        /// </summary>
        public static string login_enter_passwords {
            get {
                return ResourceManager.GetString("login_enter_passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guest ähnelt.
        /// </summary>
        public static string login_guest {
            get {
                return ResourceManager.GetString("login_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guest access cannot be changed. ähnelt.
        /// </summary>
        public static string login_guest_access_proteced {
            get {
                return ResourceManager.GetString("login_guest_access_proteced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your user name or email address. ähnelt.
        /// </summary>
        public static string login_insert_username {
            get {
                return ResourceManager.GetString("login_insert_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User name/email and password did not match. ähnelt.
        /// </summary>
        public static string login_invalid_password {
            get {
                return ResourceManager.GetString("login_invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password was not changed. ähnelt.
        /// </summary>
        public static string login_keyword_unchanged {
            get {
                return ResourceManager.GetString("login_keyword_unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your login name. ähnelt.
        /// </summary>
        public static string login_name {
            get {
                return ResourceManager.GetString("login_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwords did not match. ähnelt.
        /// </summary>
        public static string login_passwords_not_match {
            get {
                return ResourceManager.GetString("login_passwords_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User data has been changed. ähnelt.
        /// </summary>
        public static string login_userdata_changed {
            get {
                return ResourceManager.GetString("login_userdata_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Master password was changed. The program will restart now. ähnelt.
        /// </summary>
        public static string master_password_changed_restart {
            get {
                return ResourceManager.GetString("master_password_changed_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid amount. ähnelt.
        /// </summary>
        public static string missing_amount {
            get {
                return ResourceManager.GetString("missing_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter booking text. ähnelt.
        /// </summary>
        public static string missing_bookingtext {
            get {
                return ResourceManager.GetString("missing_bookingtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the city name. ähnelt.
        /// </summary>
        public static string missing_city {
            get {
                return ResourceManager.GetString("missing_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the street name. ähnelt.
        /// </summary>
        public static string missing_street {
            get {
                return ResourceManager.GetString("missing_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the zip code. ähnelt.
        /// </summary>
        public static string missing_zip {
            get {
                return ResourceManager.GetString("missing_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {1} (MySQL Server, error code: {0}) ähnelt.
        /// </summary>
        public static string mysql_error {
            get {
                return ResourceManager.GetString("mysql_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid identifier ähnelt.
        /// </summary>
        public static string mysql_invalid_identifier {
            get {
                return ResourceManager.GetString("mysql_invalid_identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name. ähnelt.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select at least one client. ähnelt.
        /// </summary>
        public static string print_select_client {
            get {
                return ResourceManager.GetString("print_select_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a printer. ähnelt.
        /// </summary>
        public static string print_select_printer {
            get {
                return ResourceManager.GetString("print_select_printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message could not be sent to {0}. ähnelt.
        /// </summary>
        public static string printpreview_email_message_failed {
            get {
                return ResourceManager.GetString("printpreview_email_message_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message was sent to {0}. ähnelt.
        /// </summary>
        public static string printpreview_email_message_sent {
            get {
                return ResourceManager.GetString("printpreview_email_message_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please configure an email address for your account first. ähnelt.
        /// </summary>
        public static string printpreview_email_missing_account {
            get {
                return ResourceManager.GetString("printpreview_email_missing_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can send email, but first you need to set up an SMTP server in the company settings. ähnelt.
        /// </summary>
        public static string printpreview_email_missing_host {
            get {
                return ResourceManager.GetString("printpreview_email_missing_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email was sent to &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string printpreview_email_send {
            get {
                return ResourceManager.GetString("printpreview_email_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File could not be created. ähnelt.
        /// </summary>
        public static string printpreview_file_create_failed {
            get {
                return ResourceManager.GetString("printpreview_file_create_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This email was created by &quot;MR Care Management&quot; and contains an important attachment for you.
        ///
        ///Contact person: {0}
        ///Phone number: {1} ähnelt.
        /// </summary>
        public static string printpreview_important_email {
            get {
                return ResourceManager.GetString("printpreview_important_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid email address. ähnelt.
        /// </summary>
        public static string printpreview_missing_valid_email {
            get {
                return ResourceManager.GetString("printpreview_missing_valid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Receipt {0} ähnelt.
        /// </summary>
        public static string quittance {
            get {
                return ResourceManager.GetString("quittance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A database transaction is already active. ähnelt.
        /// </summary>
        public static string sql_activeDatabase_transaction {
            get {
                return ResourceManager.GetString("sql_activeDatabase_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {1} (Microsoft SQL Server, error code: {0}) ähnelt.
        /// </summary>
        public static string sql_error {
            get {
                return ResourceManager.GetString("sql_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid login name ähnelt.
        /// </summary>
        public static string sql_invalid_login_name {
            get {
                return ResourceManager.GetString("sql_invalid_login_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading database... ähnelt.
        /// </summary>
        public static string sql_load_database {
            get {
                return ResourceManager.GetString("sql_load_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQL rules:
        ///1. To create a new database, always use user: sa without a password 
        ///2. First create the database, then create the users
        ///3. After creating a new database, recreate all users because the old users are no longer valid.
        ///4. Users created with this application have the following rights:
        ///- They can be used throughout the company network
        ///- they can update database entries
        ///- they can add, change and delete entries
        ///- they cannot be used with other databases
        ///5. Never try to create a database with  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string sql_rules {
            get {
                return ResourceManager.GetString("sql_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a SQL server first. ähnelt.
        /// </summary>
        public static string sql_server_required {
            get {
                return ResourceManager.GetString("sql_server_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferring advisors... ähnelt.
        /// </summary>
        public static string sql_transfer_advsisors {
            get {
                return ResourceManager.GetString("sql_transfer_advsisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferring employees... ähnelt.
        /// </summary>
        public static string sql_transfer_assistants {
            get {
                return ResourceManager.GetString("sql_transfer_assistants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferring bank bookings... ähnelt.
        /// </summary>
        public static string sql_transfer_bank {
            get {
                return ResourceManager.GetString("sql_transfer_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferring bookings... ähnelt.
        /// </summary>
        public static string sql_transfer_bookings {
            get {
                return ResourceManager.GetString("sql_transfer_bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferring cash balance... ähnelt.
        /// </summary>
        public static string sql_transfer_cash {
            get {
                return ResourceManager.GetString("sql_transfer_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferring clients... ähnelt.
        /// </summary>
        public static string sql_transfer_clients {
            get {
                return ResourceManager.GetString("sql_transfer_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferring cash count... ähnelt.
        /// </summary>
        public static string sql_transfer_coins {
            get {
                return ResourceManager.GetString("sql_transfer_coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferring deadlines... ähnelt.
        /// </summary>
        public static string sql_transfer_deadlines {
            get {
                return ResourceManager.GetString("sql_transfer_deadlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferring office petty cash... ähnelt.
        /// </summary>
        public static string sql_transfer_officecash {
            get {
                return ResourceManager.GetString("sql_transfer_officecash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferring receipts... ähnelt.
        /// </summary>
        public static string sql_transfer_receipts {
            get {
                return ResourceManager.GetString("sql_transfer_receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown error ähnelt.
        /// </summary>
        public static string unknown_error {
            get {
                return ResourceManager.GetString("unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download finished. ähnelt.
        /// </summary>
        public static string update_download_finished {
            get {
                return ResourceManager.GetString("update_download_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a new update {0}. ähnelt.
        /// </summary>
        public static string update_found {
            get {
                return ResourceManager.GetString("update_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Looking for updates... ähnelt.
        /// </summary>
        public static string update_looking {
            get {
                return ResourceManager.GetString("update_looking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error {0} while updating to version {1}
        ///
        ///{2} ähnelt.
        /// </summary>
        public static string updateFailedMSSQL {
            get {
                return ResourceManager.GetString("updateFailedMSSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while updating to database version {0}
        ///
        ///{1} ähnelt.
        /// </summary>
        public static string updateFailedMySQL {
            get {
                return ResourceManager.GetString("updateFailedMySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User was created successfully. ähnelt.
        /// </summary>
        public static string user_created {
            get {
                return ResourceManager.GetString("user_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User was deleted successfully. ähnelt.
        /// </summary>
        public static string user_deleted {
            get {
                return ResourceManager.GetString("user_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administrator accounts cannot be deleted. ähnelt.
        /// </summary>
        public static string usermanagement_admin_delete {
            get {
                return ResourceManager.GetString("usermanagement_admin_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        /// </summary>
        public static string usermanagement_Change {
            get {
                return ResourceManager.GetString("usermanagement_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        public static string usermanagement_Create {
            get {
                return ResourceManager.GetString("usermanagement_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string usermanagement_Delete {
            get {
                return ResourceManager.GetString("usermanagement_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to delete the last administrator. If you do this, the default account Admin/admin will become active again. Are you sure? ähnelt.
        /// </summary>
        public static string usermanagement_last_admin_delete_warning {
            get {
                return ResourceManager.GetString("usermanagement_last_admin_delete_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User was changed successfully. ähnelt.
        /// </summary>
        public static string usermanagement_user_changed {
            get {
                return ResourceManager.GetString("usermanagement_user_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User was created successfully. ähnelt.
        /// </summary>
        public static string usermanagement_user_created {
            get {
                return ResourceManager.GetString("usermanagement_user_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete user &apos;{0}&apos;? ähnelt.
        /// </summary>
        public static string usermanagement_user_delete {
            get {
                return ResourceManager.GetString("usermanagement_user_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete account ähnelt.
        /// </summary>
        public static string usermanagement_user_delete_title {
            get {
                return ResourceManager.GetString("usermanagement_user_delete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User was deleted successfully. ähnelt.
        /// </summary>
        public static string usermanagement_user_deleted {
            get {
                return ResourceManager.GetString("usermanagement_user_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User cannot be deleted. ähnelt.
        /// </summary>
        public static string usermanagement_user_no_deleted {
            get {
                return ResourceManager.GetString("usermanagement_user_no_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User not found ähnelt.
        /// </summary>
        public static string usermanagement_user_selected {
            get {
                return ResourceManager.GetString("usermanagement_user_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No users are available. ähnelt.
        /// </summary>
        public static string usermanagement_users_missing {
            get {
                return ResourceManager.GetString("usermanagement_users_missing", resourceCulture);
            }
        }
    }
}
